apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventhubdatamover
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventhubdatamover
  template:
    metadata:
      labels:
        app: eventhubdatamover
    spec:
      containers:
      - name: eventhubdatamover
        image: ACRcrg.azurecr.io/eventhubdatamover:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: LoadBalancer
  selector:
    app: eventhubdatamover
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
